[general]
loglevel = warning

dns-server = system,119.29.29.29,223.5.5.5

hijack-dns = 8.8.8.8:53,8.8.4.4:53,1.1.1.1:53,1.0.0.1:53

always-real-ip = dns.msftncsi.com, *.msftconnecttest.com, *.srv.nintendo.net, *.stun.playstation.net, stun.*

geoip-maxmind-url = https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-only-cn-private.mmdb

skip-proxy = 127.0.0.0/8, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, 100.64.0.0/10, 162.14.0.0/16, fc00::/7, fe80::/10, localhost, *.local, *.ts.net, captive.apple.com, passenger.t3go.cn, *.ccb.com, wxh.wo.cn, *.abcchina.com, *.abcchina.com.cn
exclude-simple-hostnames = true
read-etc-hosts = true

internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://cp.cloudflare.com/generate_204
proxy-test-udp = cp.cloudflare.com@1.1.1.1
test-timeout = 3

http-listen = 0.0.0.0:8888
socks5-listen = 0.0.0.0:8889
wifi-access-http-port = 8888
wifi-access-socks5-port = 8889
allow-wifi-access = true
proxy-restricted-to-lan = true

external-controller-access = kkchan@0.0.0.0:6170
http-api = kkchan@0.0.0.0:6171
http-api-web-dashboard = true

show-error-page-for-reject = false
block-quic = all-proxy
udp-policy-not-supported-behaviour = DIRECT
udp-priority = true
wifi-assist = false

[Replica]
hide-apple-request = true
hide-crash-reporter-request = true
hide-udp = false
keyword-filter-type = blacklist

[Proxy]

direct = Direct
HomeServer = wireguard, section-name=HongKong

[Proxy Group]
PROXY = select, 🇭🇰 HK, 🇺🇸 US
CN = select, HomeServer, 🇭🇰 HK

# Regional node group (automatic selection of the fastest)
🇭🇰 HK = url-test, policy-regex-filter=港|HK|Hong, interval=600, tolerance=50
🇺🇸 US = url-test, policy-regex-filter=美|US|States, interval=600, tolerance=50


[Rule]
# Advertisement blocking
DOMAIN-SET,https://jkoch14.me/surge-rules/private.txt,DIRECT

DOMAIN-SET,https://jkoch14.me/surge-rules/reject.txt,REJECT

RULE-SET,SYSTEM,DIRECT

# Domestic direct connection
DOMAIN-SET,https://jkoch14.me/surge-rules/icloud.txt,CN
DOMAIN-SET,https://jkoch14.me/surge-rules/apple.txt,CN
DOMAIN-SET,https://jkoch14.me/surge-rules/direct.txt,CN

# AI Serve
DOMAIN-SET,https://jkoch14.me/surge-rules/ai.txt,PROXY

# Common overseas services
DOMAIN-SET,https://jkoch14.me/surge-rules/dev.txt,PROXY
DOMAIN-SET,https://jkoch14.me/surge-rules/edu.txt,PROXY
RULE-SET,https://jkoch14.me/surge-rules/telegramcidr.txt,PROXY,no-resolve

# Domestic direct connection
RULE-SET,https://jkoch14.me/surge-rules/cncidr.txt,CN

# The bottom of the pocket
FINAL,DIRECT

[Host]
localhost = 127.0.0.1




[WireGuard HongKong]
private-key = OB8ONGzVeqWuSuzKnXsRtZ4AUGr9snvFU6Ajnfq62nc=
self-ip = 10.66.66.2
self-ip-v6 = fd42:42:42::2
dns-server = 1.1.1.1, 1.0.0.1
mtu = 1420
peer = (public-key = /6BQ3QcamJs5zeu5O3fq73BWMDIetH8OyO6K1qdDNns=, allowed-ips = "0.0.0.0/0, ::0/0", endpoint = 34.92.67.134:51820, preshared-key = mc2angem9Zjo8SfCD0FxHpCNAs/hf8FQl7drp2Z2gb4=, keepalive = 25)
